import { StatusBar } from 'expo-status-bar';
import {
  Text,
  View,
  TextInput,
  TouchableOpacity,
  ImageBackground,
  ScrollView,
  Alert
} from 'react-native';
import React, { useState, useEffect } from 'react';
import { Ionicons } from '@expo/vector-icons';
import HomeStyles from './Styles/HomeStyles';
import * as SQLite from 'expo-sqlite/next';

const TASK_ACTIONS = ['ADD TASK', 'DELETE TASK', 'EDIT TASK'];

export default function HomeScreen({ navigation, route }) {
  const [items, setItems] = useState([]);
  const [nextItemId, setNextItemId] = useState(1);
  const [editMode, setEditMode] = useState(false);
  const [accountName, setAccountName] = useState('');
  const { db, userId, displayName } = route.params;

  useEffect(() => {
    if (displayName) {
      setAccountName(displayName);
    }

    const initializeDatabase = async () => {
      if (db && userId) {
        try {
          // Create the Alert_NgoLouge table if it doesn't exist
          await db.execAsync([
            {
              sql: 'CREATE TABLE IF NOT EXISTS Alert_NgoLouge (User_ID INTEGER, Task_ID INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT, Description TEXT, Status TEXT, FOREIGN KEY (User_ID) REFERENCES LoginRequireds(User_ID))',
              args: [],
            }
          ], false);
          console.log("Alert_NgoLouge table check successful.");
  
          // Fetch tasks for the given user
          const results = await db.execAsync([
            {
              sql: 'SELECT * FROM Alert_NgoLouge WHERE User_ID = ?',
              args: [userId],
            }
          ], true);
  
          const tasks = results[0]?.rows || [];
          setItems(tasks);
          if (tasks.length > 0) {
            setNextItemId(Math.max(...tasks.map(item => item.Task_ID)) + 1);
          } else {
            setNextItemId(1);
          }
        } catch (error) {
          console.error("Error initializing database or fetching tasks:", error);
        }
      }
    };
  
    initializeDatabase();
  }, [db, userId, displayName]);

  const handleAction = (action) => {
    switch (action) {
      case 0:
        addItem();
        break;
      case 2:
        toggleEditMode();
        break;
      default:
        break;
    }
  };

  const addItem = async () => {
    const newItem = {
      User_ID: userId,
      Task_ID: nextItemId, // Consider removing Task_ID from here if it's autogenerated
      Title: '',
      Description: '',
      Status: 'Pending',
    };
  
    try {
      const results = await db.execAsync([
        {
          sql: 'INSERT INTO Alert_NgoLouge (User_ID, Title, Description, Status) VALUES (?, ?, ?, ?)',
          args: [newItem.User_ID, newItem.Title, newItem.Description, newItem.Status],
        }
      ], false);
  
      // Assuming Task_ID is auto-incremented, you don't need to set it manually
      // Update newItem based on the actual insertion result if needed
      const insertId = results[0].insertId;
      newItem.Task_ID = insertId;
  
      setItems([...items, newItem]);
      setNextItemId(nextItemId + 1);
    } catch (error) {
      console.error("Error adding task:", error);
    }
  };

  const deleteItem = async (itemId) => {
    try {
      const results = await db.execAsync([
        {
          sql: 'DELETE FROM Alert_NgoLouge WHERE Task_ID = ?',
          args: [itemId],
        }
      ], false);
  
      if (results[0].rowsAffected > 0) {
        setItems(items.filter((item) => item.Task_ID !== itemId));
      } else {
        console.log(`No task found with Task_ID: ${itemId}`);
      }
    } catch (error) {
      console.error("Error deleting task:", error);
    }
  };

  const toggleEditMode = () => {
    setEditMode(!editMode);
  };

  const handleTitleChange = async (itemId, text) => {
    try {
      await db.execAsync([
        {
          sql: 'UPDATE Alert_NgoLouge SET Title = ? WHERE Task_ID = ?',
          args: [text, itemId],
        }
      ], false);
  
      setItems(items.map((item) =>
        item.Task_ID === itemId ? { ...item, Title: text } : item
      ));
    } catch (error) {
      console.error("Error updating task title:", error);
    }
  };

  const handleDescriptionChange = async (itemId, text) => {
    try {
      await db.execAsync([
        {
          sql: 'UPDATE Alert_NgoLouge SET Description = ? WHERE Task_ID = ?',
          args: [text, itemId],
        }
      ], false);
  
      setItems(items.map((item) =>
        item.Task_ID === itemId ? { ...item, Description: text } : item
      ));
    } catch (error) {
      console.error("Error updating task description:", error);
    }
  };

  const logout = () => {
    console.log("Logging out");
    navigation.navigate('Login');
  };

  const itemViews = items.map((item) => (
    <View
      key={item.Task_ID}
      style={HomeStyles.dataContainer}
      onTouchStart={(e) => e.stopPropagation()}
    >
      <View style={HomeStyles.Data_Main}>
        <Text style={HomeStyles.dataTitle}>TASK ID: {item.Task_ID}</Text>
        <Text style={HomeStyles.label}>TITLE:</Text>
        <TextInput
          style={[
            HomeStyles.input,
            editMode ? HomeStyles.inputEdit : HomeStyles.inputNotEdit,
          ]}
          placeholder="This Title is empty"
          value={item.Title}
          onChangeText={(text) => handleTitleChange(item.Task_ID, text)}
          editable={editMode}
        />
        <Text style={HomeStyles.label}>Description:</Text>
        <TextInput
          style={[
            HomeStyles.input,
            HomeStyles.descriptionInput,
            editMode ? HomeStyles.inputEdit : HomeStyles.inputNotEdit,
          ]}
          placeholder="Description is empty"
          value={item.Description}
          onChangeText={(text) => handleDescriptionChange(item.Task_ID, text)}
          editable={editMode}
          multiline={true}
        />
      </View>
      <View style={HomeStyles.Data_Side}>
        <View style={HomeStyles.bodie}>
          <TouchableOpacity
            style={HomeStyles.body_Stand}
            onPress={() => deleteItem(item.Task_ID)}
          >
            <Text style={HomeStyles.body_font}>{TASK_ACTIONS[1]}</Text>
          </TouchableOpacity>
        </View>
      </View>
    </View>
  ));

  if (items.length === 0) {
    itemViews.push(
      <View key="no-data" style={HomeStyles.body_contain}>
        <View style={HomeStyles.bodie}>
          <TouchableOpacity
            style={HomeStyles.body_Stand}
            onPress={() => handleAction(0)}
          >
            <Text style={HomeStyles.body_font}>{TASK_ACTIONS[0]}</Text>
          </TouchableOpacity>
          <Text style={HomeStyles.dataTitle}>NO TASK PRESENT</Text>
        </View>
      </View>
    );
  } else {
    itemViews.push(
        <View key="add-data" style={HomeStyles.body_contain}>
          <View style={HomeStyles.bodie}>
            <TouchableOpacity
              style={HomeStyles.body_Stand}
              onPress={() => handleAction(0)}
            >
              <Text style={HomeStyles.body_font}>{TASK_ACTIONS[0]}</Text>
            </TouchableOpacity>
          </View>
        </View>
      );
  }

  return (
    <ImageBackground
      source={require('./assets/adaptive-icon.png')} 
      style={HomeStyles.background}
    >
      <ScrollView contentContainerStyle={HomeStyles.scrollContainer}>
        <View style={HomeStyles.container}>
          <Text style={HomeStyles.title}>ALERT&GO</Text>
          <Text style={HomeStyles.subtitle}>Bind! Grind! and Good to GO!</Text>
          <View style={HomeStyles.headbutt}>
            <TouchableOpacity style={HomeStyles.Profile_container}>
              <Ionicons
                name="person-circle-outline"
                size={40}
                color="black"
                style={HomeStyles.accountLogo}
              />
              <Text>{accountName}</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[HomeStyles.Profile_container, HomeStyles.logoutBox]}
              onPress={logout}
            >
              <Text>Log Out</Text>
            </TouchableOpacity>
          </View>
          <View style={HomeStyles.buttonContainer}>
            <Text style={HomeStyles.buttonText}>TASK STATUS</Text>
          </View>
          <View style={HomeStyles.subcontainer}>
            <View style={HomeStyles.header_body}>
              <TouchableOpacity
                style={HomeStyles.body_Stand}
                onPress={() => handleAction(2)}
              >
                <Text style={HomeStyles.body_font}>
                  {TASK_ACTIONS[2]}:{editMode ? 'ON' : 'OFF'}
                </Text>
              </TouchableOpacity>
            </View>
            {itemViews}
          </View>
        </View>
      </ScrollView>
    </ImageBackground>
  );
}